### ISSUE TITLE
Dispatch System/Queue for World Market 

### ISSUE THREAD

**Issue by BBlayne** [kingofmen/EconSim#11]
One thought I had is that for any sort of world market system that some sort of dispatch system would work better than what Victoria II has. 

Each factory at the end of the month puts its total output into a priority queue, PQ is ordered by prestige.
All trading "agents" automatically place bids. If the good is in high demand there are multiple rounds of bidding which drives up the price (or if the good is too expansive for anyone, drives the price down).
The order in which bids are made or items are placed onto the market are based off of priority queues; so higher prestige/great power ranking results in your goods being put on the market first; so for a high demand good you'll get it at the highest possible price; while everyone else after you (because people spent their money already) get paid less and accept lower bids.
Any goods that are not sold return to the stockpile to attempt to be sold at a later date.
Consistently high bids results in the base price gradually climbing in value, which affects speculation/capitalists build priorities.

**Comment by kingofmen** [comment]
I get around the major issues with the Victoria world market by not having a world market, as such; I have a bunch of local markets each with a different set of prices, and agents that transport goods between them when there is profit in doing so.
